title: "Peer Platform Documentation"
description: "Official documentation for the Peer Platform"
remote_theme: just-the-docs/just-the-docs
logo: /assets/images/logo.png

# Just the Docs configuration
just_the_docs:
  # Peer brand color
  # This sets the accent color in the sidebar, headings, links, etc.
  # See https://just-the-docs.github.io/just-the-docs/docs/configuration/
  palette:
    primary:
      accent: "#ff4e49"

# Additional site settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
